directories:
  output: dist-electron
  buildResources: build
appId: com.absensholat.desktop
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  target:
    - target: dmg
      arch:
        - universal
win:
  target:
    - target: nsis
      arch:
        - x64
        - arm64
linux:
  target:
    - target: AppImage
      arch:
        - x64
        - arm64
    - target: deb
      arch:
        - x64
        - arm64
    - target: rpm
      arch:
        - x64
        - arm64
electronVersion: 42.1.0
